on: [push]
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  test:
    runs-on: ubuntu-latest
    name: test intoto-run
    steps:
      - uses: actions/checkout@v2
      - uses: testifysec/intoto-run-action@main
        name: intoto run command
        with:
          step-name: 'build kernel'
          private-key: | 
            -----BEGIN PRIVATE KEY-----
            MC4CAQAwBQYDK2VwBCIEICmtWWk/6UydYjr7tmVUtPa7JIxHdhaJraSHXr2pSECu
            -----END PRIVATE KEY-----
          command: cd kata-containers/tools/osbuilder && sudo -E PATH=$PATH make USE_DOCKER=true AGENT_INIT=yes image
          products: 'target/release/in-toto-pipeline'
          exclude: '[".git/*",".github/"]'
      - name: show-attestation
        run: cat $RUNNER_TEMP/meta/*.link